version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: bookings
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  app:
    build: .
    environment:
      PORT: 3000
      JWT_SECRET: "dev_secret_change_me"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: nest
      DB_PASS: nest
      DB_NAME: bookings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports: ["3000:3000"]
    depends_on: [postgres, redis]
volumes:
  pgdata:
